version = 1

[[annotations]]
path = ["README.md", "*/README.md", "build/templates/index.*", "build/templates/default-index.html", ".version", "images/*.png", "images/favicon.ico"]
precedence = "closest"
SPDX-FileCopyrightText = "© 2024 Clifford Weinmann <https://www.cliffordweinmann.com/>"
SPDX-License-Identifier = "MIT-0"

[[annotations]]
path = ["build/semver"]
precedence = "closest"
SPDX-FileCopyrightText = "© François Saint-Jacques <https://github.com/fsaintjacques>"
SPDX-License-Identifier = "Apache-2.0"
