version = 1

[[annotations]]
path = ["*.md", "templates/index.*", ".version", "images/*.png", "images/favicon.ico"]
precedence = "closest"
SPDX-FileCopyrightText = "Â© 2024 Clifford Weinmann <clifford@weinmann.africa>"
SPDX-License-Identifier = "MIT-0"
